---
title: TechBikers
timezone: UTC
name: TechBikers
description: Ditch the laptop & get on your bike
footer_cta: Join us on our next ride!
collections:
  rides:
    title: Rides
    output: true
    permalink: /:collection/:title-:year/
  posts:
    title: Posts
    output: true
    permalink: /:collection/:title/
  uploads:
    title: Uploads
    output: true
future: true
donation_url: https://www.justgiving.com/fundraising/fundraisingfieldguide-charity-3
application_url: https://www.justgiving.com/fundraising/fundraisingfieldguide-charity-3
domain: matthewcobb.github.io
url:  https://matthewcobb.github.io
baseurl: /techbikers
permalink: /:title/
version: v1.0.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :compressed
plugins:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
